### ISSUE TITLE
[Deferred] SDL 0167- App Services - Structure PerformAppServiceInteraction URIs

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_evolution#678] opened 2019-02-13 21:06 UTC
Hello SDL community,

The original proposal "SDL 0167 - App Services" was accepted by the Steering Committee on 2018-05-23, alterations to the proposal have been requested through a pull request.

This review will focus on only the changes present in this pull request "SDL 0167- App Services - Structure PerformAppServiceInteraction URIs  #674 " begins now and runs through February 19, 2019.

**Note: All comments should be contained in this issue!**

The original proposal is available here:

https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0167-app-services.md

Reviews are an important part of the SDL evolution process. All reviews should be sent to the associated Github issue at:

#678

What goes into a review?

The goal of the review process is to improve the proposal under review through constructive criticism and, eventually, determine the direction of SDL. When writing your review, here are some questions you might want to answer in your review:

* Is the problem being addressed significant enough to warrant a change to SDL?
* Does this proposal fit well with the feel and direction of SDL?
* If you have used competitors with a similar feature, how do you feel that this proposal compares to those?
* How much effort did you put into your review? A glance, a quick reading, or an in-depth study?
  Please state explicitly whether you believe that the proposal should be accepted into SDL.

More information about the SDL evolution process is available at

https://github.com/smartdevicelink/sdl_evolution/blob/master/process.md

Thank you,
Jordyn Mackool

**Comment by jordynmackool** [comment] 2019-02-13 21:09
For ease of understanding, here is the new App Services - Structure PerformAppServiceInteraction URIs proposal. 

# App Services - Structure PerformAppServiceInteraction URIs

* Proposal: [SDL-0167](0167-app-services.md)
* Author: [Joey Grover](https://github.com/joeygrover)
* Status: **Awaiting review**
* Impacted Platforms: [Core / iOS / Android / Web / RPC ]

## Introduction

This PR/proposal is to add structure to the action sheet and URIs that are used in the `PerformAppServiceInteraction` RPC. It has come to our attention that structuring the data will help the app services feature be a more complete solution and introduce new use cases (widgets, app cards, etc). The structure is based on the [RFC 3986](https://tools.ietf.org/html/rfc3986) definition of URIs and new RPC messages/structs, which was created to better fit within the SDL Protocol.

## Motivation

The first iteration of the App Services features included a way for app service consumers to perform actions on the app service publisher. This was performed through a three step process.

1. When the App Service Publisher first published their service, they included both a `uriPrefix` and `uriActionSheet` in their `AppServiceManifest`. This parameter's structure was completely left up to the app service publisher. 
2. An app service consumer would retrieve the app service manifest  for a specific app service. It would then have to know how to parse the supplied `uriActionSheet` if it wished to perform a specific action.
3. The app service consumer would then fill out a URI based on the supplied information in the app service publisher's manifest and use a `PerformAppServiceInteraction` with the supplied URI to perform the action.

This change request relates to the first two steps. While it introduces the ability for app service publishers to publish any type of API they want through this mechanism, it becomes nearly impossible for an app service consumer to be compatible with all of them. By providing a structure to the action sheet, app service consumers can dynamically use a lot of the apps features without needing custom parsers.

Because structure is being added to the API, a few extra parameters will be added so that the integration steps are more feature rich. This includes the ability to add an image to an action. Also, adding a flag that lets the app service consumer know that the specific URI provided doesn't need any parameters attached and the URI can be sent to perform an action.

## Proposed solution

The proposed solution is to structure the `uriActionSheet ` and give them clearer definitions. The new structure will use the spec provided in [RFC 3986](https://tools.ietf.org/html/rfc3986) and build RPC structures around it.

Services expose their API using the `uriActionSheet` param. When defining the specific actions and URI, developers should look to the URI standard in RFC3986 and more specifically section [3. Syntax Components](https://tools.ietf.org/html/rfc3986#section-3)

`uriPrefix` + (`action.baseUri` + `action.parameters[]`) = Fully Qualified URI

#### AppServiceManifest

First thing that needs updating is the `AppServiceManifest`, for brevity it will only include the parameters that are being changed:


```xml

    <struct name="AppServiceManifest">
        <description> This manfifest contains all the information necessary for the service to be published, activated, and consumers able to interact with it</description>
        
        <param name="uriPrefix" type="String" mandatory="false">
            <description> The URI prefix for this service. If provided, all PerformAppServiceInteraction requests must start with it. This can also be referred to as the scheme of the URI. This scheme, if included, will be followed by a colon (:) as well as two slashes (//) if the service action includes a baseUri. If this is not included the uri shall start with a single slash (/). For example, uriPrefix://baseUri?parameters or uriPrefix:paramters or /baseUri?parameters </description>
        </param>
        
        <param name="uriActionSheet" type="ServiceAction" array="true" mandatory="false">
            <description> This is a custom schema for this service. Each of the actions should be formatted into a ServiceAction object that contains basic information to ensure consumers can read the data. The uriActionSheet should contain all available actions to be taken through a PerformAppServiceInteraction request from an app service consumer. If the app intends to expose Quick Action actions, the list should be ordered with the most important at index 0. </description>
        </param>
    </struct>
```
#### ServiceAction

This is the bases of the new structure. This struct was based on the RFC 3986 as close as possible while adapting it to the SDL RPC protocol. Each parameter has an accurate description of what they are and can be cross referenced with the RFC spec. 

```xml
	
	<struct name="ServiceAction">
	    <param name="baseUri" type="String" mandatory="true">
	        <description> Also referred to as the authority and path of the URI. The base URI of this action. If no params are required, this plus the URI prefix can be used as the entire URI (uriPrefix://baseUri?paramKey=paramValue&paramKey=paramValue#paramKey=paramValue). If this param is left as an empty set, it will be assumed that the params will be part of the path of the URI with no keys and the fully qualified URI will be constructed accordingly (uriPrefix:param:param:param).</description>
	    </param>
	    
	    <param name="queryParameters" type="Parameter" array="true" mandatory="false">
	        <description>An array of parameters for this action that should be included as part of the query string of the URI. When sent as a fully qualified URI these parameters will be attached in accordance to RFC3986 https://tools.ietf.org/html/rfc3986</description>
	    </param>
	    
	    <param name="fragmentParameters" type="Parameter" array="true" mandatory="false">
	        <description>An array of parameters for this action that should be included in the fragment section of the URI. When sent as a fully qualified URI these parameters will be attached in accordance to RFC3986 https://tools.ietf.org/html/rfc3986</description>
	    </param>
	    
	    <param name="isQuickAction" type="Boolean" mandatory="false">
	        <description>If set to true, this implies this action can be acted upon without an additional parameters or actions. Most common use case would be a consumer displaying a soft button to represent this action</description>
	    </param>
	    
	    <param name="icon" type="Image" mandatory="false">
	        <description>The file name of an image that can be used in association with this action. A use case for this image would be to display the action as a button on a widget. </description>
	    </param>
	
	</struct>
	
```


#### Parameter

This is an ease of use struct that will help app service consumers understand an app service publishers API in terms of what it expects. The parameters in this struct mimic the same keywords that exist in SDL's RPC spec.

```xml
<struct name="Parameter">
	    <description>Describes a parameter's attributes</description>
	    <param name="key" type="String" mandatory="false">
	        <description>The key or name to identify this parameter. If not provided it will be assumed that this parameter should be used as part of the path and a ":" delimiter should be attached before the value.</description>
	    </param>
	    
	    <param name="type" type="String" mandatory="true">
	        <description>The provided type of this object. For example String, boolean, etc. However, when put into the action URI they will all be converted to string representations.</description>
	    </param>
	    
	    <param name="isArray" type="boolean" mandatory="false">
	        <description>True if this parameter is intended to be an array of the included types, false if it is not an array.</description>
	    </param>
	    
	    <param name="isMandatory" type="boolean" mandatory="false">
	        <description>True if the parameter is required, false if it is optional.</description>
	    </param>
	</struct>
	
```


## Potential downsides

The biggest issue going from unstructured to structured is that app service publishers will be required to translate their api into the supplied structs. It is believed that the SDLC could create helpful tools for them that could take a sample URI and build the necessary structs around it. 


## Impact on existing code

Since this proposal has not yet been implemented, there is no impact on the existing code.

## Alternatives considered

- Only alternative considered is keeping the parameter unstructured.

**Comment by joeljfischer** [comment] 2019-02-18 16:07
Some thoughts:

1. For the `AppServiceManifest` it may be better to package the `uriPrefix` and `uriActionSheet` into a struct which is mandatory `false`, and then those two params can be mandatory `true`. My thinking is that if `uriPrefix` is true, then `uriActionSheet` must exist, and visa-versa. We could alternatively have the libraries spit out an exception and crash if the developer has one true and the other false.

2. The documentation for `ServiceAction/baseUri` is confusing me. What does `If this param is left as an empty set, it will be assumed that the params will be part of the path of the URI with no keys and the fully qualified URI will be constructed accordingly (uriPrefix:param:param:param)` mean? Does this mean an "empty string" instead of "empty set". It also refers to what happens if no parameters are needed, but then gives an example of a string with query parameters. I assume the example should be `(uriPrefix://baseUri)` not `(uriPrefix://baseUri?paramKey=paramValue&paramKey=paramValue#paramKey=paramValue)`. I also assume additional qualification of the paths is possible using the `/` character, but that is not described here (e.g. `uriPrefix://baseURI/path/path` where `baseURI/path/path` is passed in the `baseURI` parameter? Or should there be an additional `param` with an array of path strings? Or should the param `baseURI` be changed to `path` and made an array?

3. Can we just assume which service actions are "Quick Actions" based on the absence of `queryParameters` and `fragmentParameters`?

4. In the `Parameter` object, I'm a bit unsure about `type`. Does this mean that the value provided by the URI consumer for that key should be of that type? e.g. parameter `key = isActive`, `type = Boolean` -> consumer creates a URI of `uriPrefix://something?isActive=true`? If so, should `type` be an `enum`? Also, because it appears that the consumer still has to assemble the URI string (`PerformAppServiceInteraction/serviceURI`) themselves based on the action sheet definition, the consumer will have to understand how to assemble that themselves, unless the proxies provide helpers for that, or we provide additional structured ways to assemble that for the consumer as well as the provider.

5. In the `Parameter` object, the `isArray` and `isMandatory` parameters are optional, but without `defValue`s that I assume they should have. (Actually, same for a few of the `ServiceAction` types).

**Comment by joeygrover** [comment] 2019-02-18 21:36
1. I was debating between the options, but I think the changes are minimal.

```xml
<struct name="AppServiceManifest">
    ...
    <param name="actionSheet" type="ActionSheet" mandatory="false">
    </param>
</struct>

<struct name="ActionSheet">

    <param name="uriPrefix" type="String" mandatory="true">
         <description> The URI prefix for this service. If provided, all PerformAppServiceInteraction requests must start with it. This can also be referred to as the scheme of the URI. This scheme, if included, will be followed by a colon (:) as well as two slashes (//) if the service action includes a baseUri. If this is not included the uri shall start with a single slash (/). For example, uriPrefix://baseUri?parameters or uriPrefix:paramters or /baseUri?parameters </description>
    </param>

    <param name="uriActionSheet" type="ServiceAction" array="true" mandatory="true">
        <description> This is a custom schema for this service. Each of the actions should be formatted into a ServiceAction object that contains basic information to ensure consumers can read the data. The uriActionSheet should contain all available actions to be taken through a PerformAppServiceInteraction request from an app service consumer. If the app intends to expose `Quick Action` actions, the list should be ordered with the most important at index 0. </description>
    </param>
		

</struct>
```

2. Yes the description is filled with typos.  It should say empty string. This is to enable a specific type of URI defined in the reference spec. Personally it seems confusing, but I wanted to enable a way for it to work if members used that type of URI. Next, the example should have the params removed and another statement saying if parameters are included that specific example should follow.  The param `baseURI` is both the authority and path of the URI which include the path modifiers that you stated. It is up to the developer to supply this information as one string in this parameter. 

3. I think the specific flag is still necessary. It essentially allows the publisher to inform the consumer that this action can be used as a quick action. Just because it doesn't have params doesn't mean it should be. 

4. The consumer is required to form the complete URI themselves. This was decided as a way to not put the burden on SDL, but let the consumer perform the integration for themselves as this area will be specific on a per app service provider basis and not likely generic at all. The example provided is accurate. The type could be an enum I suppose, if we used standard types. 

5. The `defValue` tag for non-mandatory parameters results in odd behavior at times. I can add to the description that if not included it can be taken as false instead.

**Comment by joeljfischer** [comment] 2019-02-18 21:54
3. Then I think a `Quick Action` needs additional documentation, because the documentation just says that a quick action is an action that doesn't need parameters. Do you mean that something _with_ parameters could be acted upon without them anyway, or that a quick action should be handled differently than other actions without parameters?

4. Well, only certain types can be used in a URI string, right? Basically, a string, number, or boolean?

5. I'm not sure what you're referencing, but I suppose that's fine.

Also, I think that the `Parameter` type should perhaps be `ServiceParameter` for future-proofing if we another `Parameter` type is needed at some point for another area of SDL.

**Comment by joeygrover** [comment] 2019-02-18 22:02
3. Ok. `If set to true, this action should be presented to the user in a way that allows them to quickly access and use it. This infers that no additional user interaction will be required other than selecting this action.`
4. With an expansion on numer (integer, float)

I disagree. I specifically left it as a general `Parameter` as it mimics the RPC spec param model so it could be used again. It is in its most generic form so any other versions of a `Parameter` could be specified further in their naming.

**Comment by joeljfischer** [comment] 2019-02-18 22:24
I was thinking, for example, if we had a struct called `VehicleDataParameter`, or `RemoteControlParameter`, it's kind of odd to have `Parameter` be related to `AppService` without naming qualification. If you're set against it, that's fine, it just stuck out to me.

Regarding (3) quick actions, okay, I think I'm understanding where you're going. Basically you're saying that quick actions would be turned into context-sensitive UI for auto-built SDL UI, widgets, etc. while non-`quick action`s would not be turned into UI. I misread `If the app intends to expose Quick Action actions, the list should be ordered with the most important at index 0.` earlier, and I think that caused some confusion for me.

**Comment by jacobkeeler** [comment] 2019-02-18 23:02
Regarding (2), I must note that with the way that the RPC spec parser currently works, an empty string would not be allowed by Core for `baseUri`.

Core implicitly sets `minlength="1"` in String parameters if `minlength` is not included. This parameter must either be made non-mandatory (if the parameter was omitted, the `empty string` case in the description would take effect) or `minlength` needs to be set to 0 for this parameter to allow for an empty string.

**Comment by joeygrover** [comment] 2019-02-18 23:07
Good catch, didn't realize that was implicit. Is that something should be addressed in the spec itself? 

For the parameter itself it would be updated to:
```xml
<param name="baseUri" type="String" minLength="0" mandatory="true" >
    <description> Also referred to as the authority and path of the URI. The base URI of this action. If no params are required, this plus the URI prefix can be used as the entire URI (uriPrefix://baseUri?paramKey=paramValue&paramKey=paramValue#paramKey=paramValue). If this param is left as an empty set, it will be assumed that the params will be part of the path of the URI with no keys and the fully qualified URI will be constructed accordingly (uriPrefix:param:param:param).</description>
</param>
```

**Comment by jacobkeeler** [comment] 2019-02-19 16:08
1. With regards to the description for `key`:
> If not provided it will be assumed that this parameter should be used as part of the path and a ":" delimiter should be attached before the value.

I can see how this would apply to query parameters, but I don't believe that this would also apply to fragment parameters. Additionally, if we ever decide to use this struct for another purpose, this description would likely not apply in that case either. Perhaps this should be included in the `queryParameters` description instead of the `key` description.

2. Should we define what delimiters should be used for paths, query parameters, and fragment parameters in each case?

3. For documentation purposes should an optional `description` be included with the `Parameter` struct? I could see that being useful to an app developer wanting to integrate with an existing service.

**Comment by kshala-ford** [comment] 2019-02-19 16:34
I'm confused about the text that the quick actions can be used for Widgets and AppCards. Are you saying that another app which consumes the data can then present a widget on the HMI? I don't think this is what we need AppServices to be able of. Or are you saying that the HMI should consume the data to present widgets and cards? In this case I have to disagree to this proposal.

When reading the proposal I understand the idea of two applications to be able to communicate with each other. Both applications will agree on a specification how the URIs should be structured. However, I don't believe this is ever possible to be done by OEMs like us within the HMI. The parts related to widgets look to me like patched to AppServices just to have AppServices take over the widget use case. Comparing this proposal with ours, AppServices is not near to the capabilities of Widget support and multi display support.

Per this proposal the service manifest should contain all possible actions with parameters and param type. I can totally understand apps to agree on when an action is valid to be used and what values should be used. The service provider can provide a full set of possible actions to a consumer (play song, skip, start playlist ABC and hundreds of other actions). The service consumer knows about the possible actions already and can trigger the action needed.

For HMI I don't see any possibility to know possible values. I cannot see how an HMI should understand what action to present and how it should be presented. The image field that is included is way to limiting for an HMI to present something. The reason why we have display capabilities is to provide information on if images are supported and how large images should be, the aspect ratio and the supported formats. Excluding a text field and other features of soft buttons doesn't make this proposal a replacement for Widget support. I want to add the following: The moment this proposal gets new params and APIs to support all that you end up with a copy of the existing UI manipulation RPCs with soft buttons.

I don't believe this proposal is needed at all. It's adding a lot of complexity and reduces possibilities for the two apps that partner with each other. It's already the partners responsibility to already agree to a prefix, scheme and query parameters. I don't see the need to structure it and cause potential issues. I have really high doubts the service provider will be using this structure because it'll require a lot of work to add all the possible query parameters.

My suggestion is to reject this proposal in favor of Widget support as it supports far more capabilities to any kind of app. Widget support is back and review ready https://github.com/smartdevicelink/sdl_evolution/pull/670

**Comment by joeygrover** [comment] 2019-02-19 16:56
Hi @kshala-ford thanks for your feedback!

These is a pretty long feedback so I will attempt to address issues as I can.
One of the main purposes of the proposal was to expose an app as a service for  all app consumers, including the HMI. This allows the HMI to fully integrate an app into the UX and outside the hardlined template design. HMIs can include information into clusters, second screens etc. It does not intend to replace the mainline UX that is provided through the app's generic integration though. An HMI does not have to consumer data in this way if it doesn't wish either. 

>The parts related to widgets look to me like patched to AppServices just to have AppServices take over the widget use case. Comparing this proposal with ours, AppServices is not near to the capabilities of Widget support and multi display support.

If you read the original proposal you will see this is always what was intended for this parameter. So any proposal after the agreeance on this proposal should take that into consideration. 

>Both applications will agree on a specification how the URIs should be structured.

How will they agree? There is no negotiation here. It is simply the provider saying "Here this is what I can do, and how to do it." The idea with quick actions is that the consumer can use those as an easy way for integration with some control over the provider's app. 

>For HMI I don't see any possibility to know possible values.

That is the idea behind the quick action tag. The HMI doesn't need to know any values. It simply uses the URI as is in a `PerformAppServiceInteraction` to accomplish this action. As stated in the description each of those options should be ordered in their importance to display. 

>Excluding a text field and other features of soft buttons doesn't make this proposal a replacement for Widget support.

I don't believe I said that. I merely stated that it can be used for such a feature. There is no hardline saying this is the only way widgets can be supported.  

>: The moment this proposal gets new params and APIs to support all that you end up with a copy of the existing UI manipulation RPCs with soft buttons.

Would you rather send soft button RPCs to each app consumer? How does that work across multiple phones and HMIs? 

>I don't see the need to structure it and cause potential issues.

Can you explain further the potential issues? I would much rather address such concerns than be left to defend against "possibilities".


>I don't believe this proposal is needed at all. It's adding a lot of complexity...

I agree it adds complexity, however I think it's important to structure this data so we can expose some further integration possibilities. As always, I can see a manager taking the brunt of the work off the provider given they follow the standard URI definitions. Parsing a JSON action sheet into the necessary params would not be difficult.

>My suggestion is to reject this proposal in favor of Widget support as it supports far more capabilities to any kind of app. Widget support is back and review ready #670

I don't believe your proposal provides enough of a complete working background on the multi screen support to agree to this. I also don't believe they can't coexist.

**Comment by ashwink11** [comment] 2019-02-19 16:57
1.  I guess "An app service consumer" in IVI would be HMI. Please let me know, if my understanding is incorrect. Are there any restrictions on Number of services exposed by an App? In case App provides 10 ServiceAction, how should HMI decide which ones to show? or is it expected that HMI will consume all of them?

2. Is there any way for Apps to know, how these ServiceActions & Service Data will be shown in HMI? OEM's might have a different strategies to show information in Widgets/AppCards. For example, if string provided by Struct MediaServiceData is too large or too small for the textfields on HMI, Is it possible for an App to know, the text fields capability so that they can decide which data to be shown?

**Comment by joeljfischer** [comment] 2019-02-19 17:07
An addition to `ServiceAction` I'd like to see is `name` or `title` (e.g. human readable) in addition to `icon`. Buttons sometimes may not be capable of displaying an icon, when they display a name. I'm thinking of a second-screen interface that is capable of displaying a long but short menu. It may or may not be able to display the icon (because of the long rectangular shape of each menu item) but would be able to display text.

**Comment by mjuarez-ford** [comment] 2019-02-19 17:07
Some questions:
1.	Is this proposal is only going to work with parameters in the URL?
2.	How it is going to work the mapping between URLs and interactions?
3.	How the consumer will know how parse the data that is coming?

**Comment by joeljfischer** [comment] 2019-02-19 18:01
@ashwink11 
1. Correct, an app service consumer could be the IVI or another app.
2. There is no current restriction on the number of `ServiceAction`s exposed, if that's what you're asking. The HMI decides which ones to show based on the `isQuickAction` boolean and their placement within the array (closer to index 0 == more priority). It is not expected that an HMI will necessarily consume any! An HMI could consume none, the first quick action, additional quick actions, or even have specialized integrations with an app to consume actions with parameters.

@mjuarez-ford
1. Yes, it will be assembling URL strings, so it will only work with parameters that can be passed in a URL.
2. The app will handle that, perhaps with additional proxy library assistance.
3. That's the app's job, they will simply parse the URL string using built in operating-system level tools, or the proxy library will assist.

**Comment by joeljfischer** [comment] 2019-02-19 18:05
@kshala-ford Reading between the lines here, I'd like to add on to what @joeygrover said.

First, this is not precisely a replacement for your widget support proposal. Second, this is for two apps, _or an app and an HMI_ to communicate. Third, a lot of your confusion seems based on what I was confused about, namely, quick actions. Quick actions are prioritized actions which don't require parameters and are chosen actions from the developer for what kinds of buttons the HMI (or another app) could display related to the app service. As I noted above, I believe actions should have an optional human-readable `name` or `title` as well.

Whether or not widget support is accepted, I think this is overall a logical and needed addition to actions in app services.

**Comment by robinmk** [comment] 2019-02-19 20:42
I see this proposal as being an extension to the overall AppServices framework - enabling app to app communication- and the benefits that come along with it.
However, I am unsure if this would fit well as a solution for a head unit's Widget/AppCard concepts. We feel the Widgets/AppCards should be addressed more exclusively and would like to bring our thoughts through an upcoming proposal – Widget Support [#670](https://github.com/smartdevicelink/sdl_evolution/pull/670)
If Widgets/AppCards are key aspects for the acceptance of this proposal, I would like to suggest deferral till the review of the 'Widget Support' proposal is completed.

**Comment by joeygrover** [comment] 2019-02-19 21:01
@robinmk due to the timeline of App Services being a Q1 feature and Widget Support not having any placed timeline I don't believe that is good path forward. I also see the Widget Support proposal and subsequent multi screen proposals taking an enormous amount of time to get through. 

As stated previously, both solutions can work together just fine. #670 is a much broader topic on managing multiple screens from an apps point of view which his going to take a lot of heavy lifting on the app's point for book keeping. This proposal is essentially allowing **any** consumer to create a deeper integration with that app without the app having to manage those states. I believe some head units will build out widgets and cards that can be based on service type rather than generic apps. This would allow the UI to maintain some static identity if the app was not connected during the next session. 

I believe this feature is a necessary piece into the App Service framework in general and while it can be used for things like widgets and app cards it is not exclusive to them nor are they required to be implemented in such a way.  

Also please note, the overall App services proposal has been accepted and this feature will exist, however, I feel in a more difficult to implement way. So at this point it seems there might be more concern that this change to the App Service proposal will somehow prevent the Widget Support proposal from being accepted, and again I say that is not the case.


To address other concerns:

@jacobkeeler 
1. I agree that should likely be moved to the array instead of the actual param struct as it doesn't make sense there
2. i don't think so, these are pretty standard based on the referenced spec
3. I believe you and @joeljfischer are getting at the same thing and I agree. I think adding a String param to the struct makes sense. `title` or `text` works for me.

**Comment by kshala-ford** [comment] 2019-02-19 21:45
@joeygrover based on your above comment this is the exact reason why I asked to clearly differentiate the current status of the Services markdown file and this specific proposal regarding URIs.

There's no issue with timing looking at the current version of the Services markdown file. We cannot accept forcing this proposal to get through without evaluating the downsides of this proposed variant of  having URIs between apps.

> As stated previously, both solutions can work together just fine.

True to the current markdown file. Wrong to this proposal. We need to have both examined carefully so that the SDLC understands the purpose and that this proposal stays in conflict.

**Comment by joeygrover** [comment] 2019-02-19 21:47
@kshala-ford I guess there is just misunderstanding in how this proposal works then. I ensured when crafting it that it was still in line with what you had in mind for your multi screen proposals. The changes here have no effect on your widgets proposal's ability to function. As stated a few times now, the HMI does not have to use this feature at all.

**Comment by joeygrover** [comment] 2019-02-19 21:49
>There's no issue with timing looking at the current version of the Services markdown file.

Unfortunately there is, as this change is changing a param type it would be a breaking change. That is why I brought it up.

**Comment by kshala-ford** [comment] 2019-02-19 21:50
It's not a breaking change when deprecating and replacing it with a new parameter.

**Comment by lauratonwe** [comment] 2019-02-19 21:51
@joeygrover we have changed the widgets proposal and it is marked ready for review and we intend to ask that it be pulled in for review for next week.  It has been changed from the previous proposal and should be reviewed along with this proposal.

**Comment by joeljfischer** [comment] 2019-02-19 21:57
This proposal seems to improve app<->app communication and app<->hmi communication in the context of app services. I'm sorry, but it seems to me that Ford's only downside to this proposal is "it's not the widget proposal." But as noted by the author multiple times, this proposal is not a full multi-screen addition to app services, it's an improvement to how actions work in the context of app services _for all app service use cases_.

* Does it enable an HMI to create a widget interface if so desired? Yes.
* Does it enable "widgets" with the power of the widget proposal? No.
* Does it enable a full multi-screen experience? No.
* Can these proposals coexist if both are accepted? Yes.

**Comment by kshala-ford** [comment] 2019-02-19 21:59
* Does it enable an HMI to create a widget interface if so desired? No because it doesn't include rendering meta-data.
* Does it enable "widgets" with the power of the widget proposal? No.
* Does it enable a full multi-screen experience? No.
* Can these proposals coexist if both are accepted? The question is rather: Is it mandatory to extend the action sheet to this extend if HMI is not a candidate of using the actions?

**Comment by lauratonwe** [comment] 2019-02-19 21:59
@joeljfischer in order to understand how the two proposals will "play well" together, we need to review them both together.  Approving one before the other is reviewed will not allow us a thorough analysis.  We are asking to defer this proposal another week so that it can be reviewed along side the widget proposal which is ready for review and we intend to request be brought in for review for next week.

**Comment by joeljfischer** [comment] 2019-02-19 22:02
@kshala-ford I don't think you understand the totality of app services (it's a large proposal). App services in general does include metadata.

Of course the HMI is a candidate to use actions, unless we propose arbitrary limitations to app services.

@lauratonwe That is an absurd argument. Reviewing both together is not necessary to know if they "play well." We've all read both.

**Comment by lauratonwe** [comment] 2019-02-19 22:04
@joeljfischer "absurd" seems a bit strong :)   Our widgets proposal has been revised.  We have changed it.  You have not read the changed version and would need to review it.  We are suggesting it be reviewed along with this proposal to make sure there are no incompatibilities.

**Comment by joeljfischer** [comment] 2019-02-19 22:06
I have read both. They're compatible.

**Comment by lauratonwe** [comment] 2019-02-19 22:10
That may end up being the case.  We want time for further analysis.  We are asking that the proposals be reviewed together.  Since our proposal will be brought in for review for next week this is not an unreasonable request given the complexities.

**Comment by jordynmackool** [comment] 2019-02-20 22:27
The Steering Committee voted to differ this proposal to allow greater discussion between SDLC members in hopes to align on what this proposal needs to be complete. To ensure that the next release deadline is met, it was concluded that the author is to submit a PR to remove the URI parameters (URI prefix and URI scheme) from the app service manifest so there is no need to force a breaking change in the future. The Q1 release will have will have the PerformAppServiceInteraction RPC available still, which can send a URI as a string if the app consumer had the schema at compile time.
There was a great deal of discussion regarding the similarities with this proposal and the 0216 Widget Support proposal. It was stated by Ford that a point of concern with this proposal is that the new structure would add complexity to the provider. In past experiences with app developer, both partners work together to agree on URIs and schema prior to run time. The example was given of Waze Audio Player that works together with some partners like iHeart radio and Pandora, they are using the URI scheme in order to communicate with each other. With structuring the URI, there is a concern the provider will have to update this structure over and over again for any case of the current status of the application (as an example, you are a media application and you want to provide URIs, the media service would need to update the service meta data in every state change of the application or it is agreed to have all the possible URIs in this meta data.
In response to Fords concern, the PM noted that URIs already exist and were accepted in the 0167 - App services proposal. Apps are not required to update the action sheets, but can if they need to. As it shouldn’t happen very often it wouldn’t be a big deal.  If an app used a URI that is not currently accepted, the action would just be returned with an error using the action response (saying this does not work because the user is in radio). Additionally, the URI actions are not mandatory, while we are exposing this functionality, it is not mandatory for the app service provider to actually publish their action sheet.
Ford stated it believes the current structure is not sufficient for an HMI to properly render and present an action on the screen for the user or having a voice command in order to perform this action.
The PM responded that this does not cover all application cases; this proposal just exposes a way in which the specific app services can expose quick URI actions to its consumers. It can work side by side with the larger widget proposal put forth by Ford, and HMI’s are not required to implement this part of the App Service proposal.

**Comment by theresalech** [comment] 2019-04-24 15:08
The Steering Committee voted to close this proposal, as a new proposal will need to be entered to reflect the already implemented App Services feature.

**Closed by theresalech** 2019-04-24 15:08 UTC
Labels: core, deferred, ios, java suite, rpc
